# Dockerfile
#
#
# Base quantal build

FROM	ubuntu:quantal
MAINTAINER	Neal Hardesty <nealhardesty@yahoo.dot.com>

RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal main restricted" > /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal main restricted" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal-updates main restricted" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal-updates main restricted" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal-updates universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal-updates universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal-updates multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal-updates multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ quantal-backports main restricted universe multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ quantal-backports main restricted universe multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://security.ubuntu.com/ubuntu quantal-security main restricted" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://security.ubuntu.com/ubuntu quantal-security main restricted" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://security.ubuntu.com/ubuntu quantal-security universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://security.ubuntu.com/ubuntu quantal-security universe" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://security.ubuntu.com/ubuntu quantal-security multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://security.ubuntu.com/ubuntu quantal-security multiverse" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb http://extras.ubuntu.com/ubuntu quantal main" >> /etc/apt/sources.list'
RUN bash -c 'echo "deb-src http://extras.ubuntu.com/ubuntu quantal main" >> /etc/apt/sources.list'

RUN bash -c 'echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu quantal main" > /etc/apt/sources.list.d/webupd8team-java-quantal.list'

RUN apt-get update

RUN echo "yes" | apt-get install -y --force-yes oracle-java6-installer


ENV JAVA_HOME /usr/lib/jvm/java-6-oracle

RUN java -version
