version: '2'

services:
  spark:
    build: .
    command: /start-spark-master.sh
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "/tmp:/shared"
  spark0:
    build: .
    command: /start-spark-slave.sh
    depends_on:
      - spark
    ports:
      - "8081"
    volumes:
      - "/tmp:/shared"
  spark1:
    build: .
    command: /start-spark-slave.sh
    depends_on:
      - spark
    ports:
      - "8081"
    volumes:
      - "/tmp:/shared"
  spark2:
    build: .
    command: /start-spark-slave.sh
    depends_on:
      - spark
    ports:
      - "8081"
    volumes:
      - "/tmp:/shared"
  spark3:
    build: .
    command: /start-spark-slave.sh
    depends_on:
      - spark
    ports:
      - "8081"
    volumes:
      - "/tmp:/shared"
