apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
    external-dns.alpha.kubernetes.io/ttl: "60"
  labels:
    app: quakejs
  name: quakejs
spec:
  ports:
  - port: 27960
    protocol: TCP
    targetPort: 27960
    name: tcp-quake
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-quake
  selector:
    app: quakejs
  type: LoadBalancer
