FROM kafka
MAINTAINER nealhardesty@yahoo.com

ADD ./lib/kafka01.server.properties /etc/kafka/kafka01.server.properties
ADD ./lib/kafka02.server.properties /etc/kafka/kafka02.server.properties
ADD ./lib/kafka03.server.properties /etc/kafka/kafka03.server.properties
ADD ./lib/kafka04.server.properties /etc/kafka/kafka04.server.properties
ADD ./lib/kafka05.server.properties /etc/kafka/kafka05.server.properties
ADD ./lib/kafka06.server.properties /etc/kafka/kafka06.server.properties


# 2181 and 9092 are in the base image
EXPOSE 9093
EXPOSE 9094
EXPOSE 9095
EXPOSE 9096
EXPOSE 9097
